/* seed-world-dossier-full.macro.js — World Dossier, full corpus seed (2026-07-03)
 *
 * 41 entity pages drafted from the live campaign's 545 beats + narrative
 * journals (evidence-grounded, spoiler-gated). Companion review doc:
 * ~/badeden-bible/new-content/world-dossier-drafts-2026-07-03.md
 *
 * Conventions (parsed by bbttcc-mal-voice/scripts/npc-dialogue.js):
 *   @knownBy: <who, who, …>   actor name / actor id / faction:<name> / all
 *   @after: <questId>[:completed]   page invisible until the story arrives
 * Pages whose @knownBy names communities with no matching actors yet (the
 * Tanneritos, Khezek Tor miners…) are DORMANT by design — they activate the
 * day such actors exist, and until then no NPC wrongly knows vault/mall
 * interiors.
 *
 * DRY_RUN default true. Existing pages are SKIPPED unless ALLOW_OVERWRITE —
 * flip it to replace the two prototype stubs (Dougan Marsh, The Gullywasher)
 * with the richer drafts, but only if you haven't hand-edited them.
 * Run as GM. Reopen any open NPC dialogue windows afterward to pick up pages.
 */
(async () => {
  const DRY_RUN = false;            // set false to write
  const ALLOW_OVERWRITE = false;   // true = update pages that already exist

  const JOURNAL_NAME = "World Dossier";

  const PAGES = [
    // ── The Jackalopes — people ────────────────────────────────────────────
    { name: "Mara Quickhands", knownBy: "Mara Quickhands, faction:The Jackalopes", after: null, body:
      `Mara Quickhands — "Quick-Hands" — is floor boss and fixer of the Jackalope Exchange at Furrier's Fixit Farm, and a Jackalope through and through. She runs the Exchange day to day, working the Counter, where every deal, promise, and scrap of information passes. She does not quote numbers; she quotes the weight of a relationship. She remembers every bargain she has ever made and every one she has regretted. She speaks fast, listens faster, and does not repeat herself. Trade is her element, and she handles serious business like the Leyline Stabilizer herself. She has a trickster streak — "wascawy," by her own account — and hops off when she is done with you. She keeps company with Dougan, Miliard, Young Gearbox, and the runners Pip and Patter.` },
    { name: "Mara Quickhands — When a Runner Doesn't Come Home", knownBy: "Mara Quickhands, faction:The Jackalopes", after: "quest_NwiADv8ZDoklqwEJ", body:
      `When one of the runners fails to return from the newly found Vault, Mara stops smiling. She does not panic and she makes no announcement — among the Jackalopes, word spreads sideways. But the loss reaches her: for once her thumb stops clicking, and she comes looking herself. "I don't need heroes," she says. "I need to know if I should start grieving or start sharpening." She cares more for her people than she lets the Counter show, and marking that Vault on a map costs her something, though she keeps her voice terse.` },
    { name: "Dougan Marsh", knownBy: "Dougan, faction:The Jackalopes, all", after: null, body:
      `Dougan Marsh runs the Gullywasher, a saloon in the Jackalope Exchange at Furrier's Fixit Farm. He is a Chupacabra — and an outlier among his kind: a genuinely decent sort who gets along with nearly everybody, which is not what folk brace for when a Chupacabra walks in. Dapper, fanged, and theatrical, he deals fair, keeps fair company, and is slow to anger. He trades in atmosphere rather than gossip, pours things like rosemary-infused radish gin, and hosts poetry readings on Wednesdays with cross-species attendance encouraged. He holds that culture can anchor a place as well as iron. He speaks warmly of the Jackalopes — he has tasted their wine, "mediocre but earnest" — and insists the old Chupacabra-Jackalope enmity was staged by someone who profits from inherited hatreds, and is no natural thing.` },
    { name: "Dougan Marsh — What He Really Is", knownBy: "Dougan, faction:The Jackalopes", after: "fc_wendigo_confluence", body:
      `Dougan is more than an odd Chupacabra. He is an Echo — spun from a forgotten diplomat who died trying to broker peace between warring communities. It explains his calling: he believes even myths deserve revision, and that the Chupacabra-Jackalope feud is grief being carried badly by someone else, all interest and no principal. He points those he trusts upstream, to where the leylines knot, to recover the true original injury beneath the quarrel. He means to set a long table — a Chupacabra at one end, a Jackalope at the other — and finish the peace his first life could not. Being asked to take a side dims him; holding the room steady is what he asks of others.` },
    { name: "Pip", knownBy: "Pip, faction:The Jackalopes", after: null, body:
      `Pip is a young Jackalope runner at Furrier's Fixit Farm, one of an inseparable pair with Patter — the two are impossible to tell apart unless you already know them. Together they move messages, light cargo, and rumors between the hexes, and much of the region's reputation spreads through them. Pip is motion incarnate: he talks with his hands, leans in too close, and smiles like the world is something you can talk down if you just keep it busy. He believes the world can still be understood. Where Pip pushes forward to keep things alive, Patter pulls back so they both survive — if Pip is talking, Patter is watching; if Patter is talking, Pip has already moved. When Pip goes quiet, nobody likes it. The pair never travel entirely alone.` },
    { name: "Pip — The Runner in the Loop", knownBy: "Pip, faction:The Jackalopes", after: "quest_NwiADv8ZDoklqwEJ", body:
      `Pip went out to the newly found Vault on a routine run and did not come back, though he always comes back — always. Patter wears a groove into the Fixit Farm floorboards waiting. Inside the Vault, Pip triggered a training lockdown and became trapped in a repeating tactical scenario built to reward speed, decisiveness, and acceptable loss. Pulled out early he is shaken but whole. Left in longer he carries a hard new lesson, with something changed behind his eyes. Left too long he is lost to the Vault entirely, becoming one of its flitting training echoes — a Jackalope-shaped ghost Patter can at least still visit.` },
    { name: "Patter", knownBy: "Patter, faction:The Jackalopes, all", after: null, body:
      `Patter is one of the two young Jackalope couriers, Pip and Patter, who move messages, light cargo, and rumors between the hexes around Furrier's Fixit Farm. The pair are impossible to tell apart unless you already know them. Patter is stillness itself: eyes always moving, listening longer than necessary, speaking as though each word carries a weight limit. Where Pip pushes forward to keep the world alive, Patter pulls back so the two of them survive. Patter notices patterns in chaos and believes the world must be managed. If Pip is talking, Patter is watching; if Patter is talking, Pip has already moved. Much of what the enclave knows, and much of its reputation abroad, travels through the pair of them.` },
    { name: "Patter — After Pip's Run", knownBy: "Patter, faction:The Jackalopes", after: "quest_NwiADv8ZDoklqwEJ", body:
      `Pip and Patter are never late. They do not get lost, and they do not miss a check-in. So when Pip goes out to the newly found Vault and does not come back, Patter changes. Patter stops smiling, stays at the Fixit Farm, and wears a groove into the floorboards, hyper-focused and brittle. Patter waits, and Patter will know exactly how long anyone else waited too. Pip always comes back. Always.` },
    { name: "Miliard", knownBy: "Miliard, faction:The Jackalopes", after: null, body:
      `Miliard is a Jackalope of the Fixit Farm enclave and its resident showman — a theatrical sort with a flair for performance and, by his own cheerful admission, "a LOT." He counts Mara among his conspirators and Dougan among his drinking partners; the two keep a running tally of beers owed. He will throw himself fully into a role for the good of the enclave, and takes pride in his gift for stirring strong reactions from an audience. Warm, dramatic, and quick on his feet, he is the kind who bows on his way out the door.` },
    { name: "Miliard — The Weeping Prisoner", knownBy: "Miliard, faction:The Jackalopes", after: "quest_uDuNp2yQxbuKkHx7:completed", body:
      `The bound, bleeding "thief" the Jackalopes present for judgment is Miliard, playing a part. The whole captive scene is a ruse — a test the enclave runs on newcomers to see how they hand out justice, mercy, or punishment. When it ends, Miliard slips his own bonds, stands, and cheerfully takes his leave, collecting five beers from Dougan for the performance. He regards churning the stomachs of onlookers as one of his greatest gifts. The Jackalopes call such trickery their nature — "we're wascawy" — and mean no lasting harm by it.` },
    { name: "The General", knownBy: "The General, faction:The Jackalopes, all", after: null, body:
      `The Jackalopes are led by a figure known only as The General. He is not a Jackalope — he is a Furrykin: tall, scarred, and unsettlingly calm. He does not explain how he came to lead them, and no Jackalope will answer questions about it directly. When The General speaks, the Jackalopes listen; when he stops speaking, plans are already in motion.` },
    { name: "Furrier", knownBy: "Furrier, faction:The Jackalopes, all", after: null, body:
      `Furrier is the eponymous founder of Furrier's Fixit Farm and the keeper of the Ledger. Among the Jackalopes he is a legend — old enough that he cannot possibly still be alive, and yet somehow he is. Somewhere in the Exchange he keeps the Ledger, the record where Jackalopes set down their debts, favors, and slights. He is rarely seen directly; his hand is felt through what the Ledger holds and what it settles. To the Jackalopes, Furrier's quiet presence works like a pressure gauge for the whole Farm — a measure of what is owed, what is owned, and whether the place is holding.` },
    { name: "Old Gearbox", knownBy: "Old Gearbox, faction:The Jackalopes", after: null, body:
      `Old Gearbox is the master mechanic of Furrier's Fixit Farm, tending the generator hall where massive turbines spin under heavy housing. He has been here since before the Jackalopes ever claimed the place, and he does not care who runs it so long as the generators stay on. He moves through the hall like a priest through ritual space. He trusts competence, not ideology — "Generators don't care who's in charge," he says. "I respect that." He speaks in short, flat statements, and no one is allowed into his hall unescorted; an invitation is never casual. Lately his work has grown careful and redundant, shielding and dampeners added as if bracing for some coming load.` },
    { name: "Young Gearbox", knownBy: "Young Gearbox, faction:The Jackalopes", after: null, body:
      `Young Gearbox works the Arc Bay at Furrier's Fixit Farm, amid the sparks, the rigs, and the war machines. He handles the heavy gear and hardware, and the deals that come with it — though for anything serious he wants Mara Quickhands at the table. His manner is dry and unbothered: "You break it, you buy it. It breaks you, you buy it. Manner of payment TBD." He keeps working while he talks, rarely looking up from whatever mech he is fiddling with. He is the one holding the Leyline Stabilizer that newcomers come to the Farm looking for.` },

    // ── The Fixit Farm cluster — places + the Wendigo ─────────────────────
    { name: "Furrier's Fixit Farm", knownBy: "all", after: null, body:
      `Furrier's Fixit Farm is a working settlement and trade stop run by the Jackalopes, built into a half-collapsed pre-Fall factory patched with sheet metal and railcar doors. Wind chimes of shell casings and old keys clatter over the bay door, which reads "Fixit and Goods." It is exactly what it sounds like, and more dangerous than it looks. Under one roof it keeps the Gullywasher saloon, a General Store where Mara Quickhands weighs relationships as readily as coin, the Arc Bay where the Gearboxes build and mend rigs and war machines, and a Generator Hall that runs against all odds. A working Leygate stands here too. The Farm trades freely across the region, and places like Port Kudzu and Allesh-Gilliam quietly lean on Jackalope logistics more than they admit. Runners Pip and Patter move messages and light cargo between the hexes.` },
    { name: "The Gullywasher", knownBy: "all", after: null, body:
      `The Gullywasher is the saloon at Furrier's Fixit Farm, run by Dougan Marsh, a Chupacabra bartender and an unusual one: fair company, fair dealing, slow to anger, and on good terms with nearly everyone, which is not what folks brace for when a Chupacabra walks in. Ley sigils glow in the tabletops. Dougan curates atmosphere more than gossip, pours tasting flights, and hosts poetry readings on Wednesdays with cross-species attendance encouraged. He holds that the old Chupacabra-Jackalope war was staged by someone who profited from it, and that culture can anchor a place as well as iron. He greets newcomers as revisers of stories rather than conquerors, and counsels visibility, hospitality, and setting a table for those who should not feel welcome. Lately he speaks of the Gate being unsettled, remembering something incorrectly.` },
    { name: "The Leygate at Furrier's Fixit Farm", knownBy: "all", after: null, body:
      `A working Leygate stands at Furrier's Fixit Farm, one of the few anyone trusts to run, which is part of why the Farm matters to the whole region. Lately it hums like someone pretending they aren't tired, its light flickering blue to yellow and back. The stabilizer readout shows turbulence, not failure but stubborn persistence. The engineers do not find this reassuring. The trouble is not that the Gate might explode; it is that it might misfire and remember wrong, sending the wrong shape of thing. The same sickness runs in the Allesh-Gilliam gate downriver, which is why the new custodians there have come seeking a replacement stabilizer. The Jackalopes hold one, and the Gearboxes and Mara Quickhands drive a hard bargain over it. Some here say culture can anchor a leyline as surely as iron.` },
    { name: "The Wendigo", knownBy: "all", after: null, body:
      `The Wendigo are the regional dread of the leyline roads. Travelers meet them out past broken bridges, acid bogs, and radiation pockets, where they appear as gracious, orderly, unnervingly polite hosts who will pause to give directions around a hazard. They are also spoken of in whispers as things that warp space, time, and the souls of others, and rumor piles worse on them still: skinning souls, eating babies, feasting on the righteous and unrighteous alike. What everyone agrees on, kind account and cruel account alike, is that there is something OFF about them, a missing piece no one can name. Nobody sensible lingers to learn what. Folk avoid the leyline knots where they are thickest and hurry past when the kindness feels a beat too smooth.` },
    { name: "The Wendigo — the truth", knownBy: "all", after: "fc_wendigo_confluence", body:
      `The Wendigo are not evil. They are mercy misapplied. Where the collapsed leylines knot, at the Confluence, they keep a long table set with a handwritten name-card at every seat, one for each person the region has forgotten. They are not hoarding the forgotten; they are holding them, waiting for someone to come back for what they kept. Their hospitality is real, and so is the trap inside it: to sit is to be occupied, not haunted. Someone has been doing the region's grieving for it, and doing it badly, and the Wendigo are that someone. Among the debts they hold is the original injury behind the old Chupacabra-Jackalope feud, the reason a people cannot stop hating itself, smoothed over so long that only the hatred remains. Give the leyline back its foundation and they can finally let go.` },

    // ── Allesh-Gilliam ─────────────────────────────────────────────────────
    { name: "Allesh-Gilliam", knownBy: "all", after: null, body:
      `Allesh-Gilliam is the coalition's fortress hold, an East Texas town rebuilt from wreckage that refused to finish dying. Its walls are welded from overturned semis, refinery plate, and the remains of old water towers — nothing matching, everything working — and a hand-painted sign above the gate carries the two joined names. Within the walls stands Saint Gilliam's, a candlelit house of rest and refuge kept by Father Tamsin of the Order of the Holy Turnpike. Its leygate runs restless of late, the same unquiet that troubles the gate at Furrier's Fixit Farm. The town keeps a plain creed: hold fast, pay debts, don't lie to the land.` },
    { name: "Gilliam", knownBy: "all", after: null, body:
      `Gilliam is one of the two namesakes of the frontier hold Allesh-Gilliam, an East Texas town rebuilt from wreckage that refused to finish dying. Of the pair, Gilliam is the one remembered in worship. Saint Gilliam's stands within the town walls, a candlelit house now kept as rest and refuge by Father Tamsin of the Order of the Holy Turnpike. People pray there whether or not they still believe, and quiet agreements are struck among its candles; some say the land listens more closely in that room than anywhere else in town. Gilliam's name is always spoken alongside Allesh's, the two bound together in the hold they share. Beneath the joined names the town keeps a plain creed: hold fast, pay debts, don't lie to the land.` },
    { name: "Allesh", knownBy: "all", after: null, body:
      `Allesh is one of the two namesakes of the frontier hold Allesh-Gilliam, joined in name with Gilliam on the hand-painted sign above the town's gate. Unlike Gilliam, who is remembered as a saint with a church of his own, Allesh keeps no shrine and little settled story; the name endures chiefly through the town it helps to name. Locals speak the two names together as one breath, and both stand beneath the hold's plain creed: hold fast, pay debts, don't lie to the land.` },

    // ── Regional notables ──────────────────────────────────────────────────
    { name: "Captain Robot", knownBy: "all", after: null, body:
      `Captain Robot leads the Circuit Riders, a mobile coalition of modular bikes and crawler-rigs that patrols failing relay networks and intervenes where drift becomes lethal. He wears a patched, lovingly maintained robot suit and speaks through a voice grill with measured, unhurried dignity. His doctrine runs in strict order: verification first, friendship second, rescue third. He warns that Darkness now imitates efficiency, arriving as cleaner, faster, colder choices that quietly hide what they leave out. He promises no sentiment, only response. If an alliance is genuine and the call is clean, the Riders come hard and fast, without theatrical delay. His crew of robots reveres him as their metallurgical father.` },
    { name: "Gilbert", knownBy: "the Popcorn Council, Lars von Replicator", after: null, body:
      `Gilbert is a demon in theater-attendant dress who haunts the Bad Eden Bijou, an old movie house within the Hidden Vault. Summoned long ago for an opening-night party that never manifested, he was trapped by the Shattering and now runs the place through frantic lists of demands, trivia quizzes, and personality tests, endlessly preparing for a screening no one will attend. Beneath the panic lies real duty and care; he is as much a victim as anyone, if a less sympathetic one. He terrifies the vault's sentient appliances, the Popcorn Council and the matter replicator Lars von Replicator. He can be fought, controlled, or released. Calmed, he becomes a gracious Assistant Manager.` },
    { name: "Kickflip Lazarus", knownBy: "the Tanneritos", after: null, body:
      `Kickflip Lazarus is a skatepark spirit haunting the old mall frequented by the Tanneritos, less a single person than the accumulated will of generations of kids trying to become themselves in the same square footage. Thin, staticky, hooded, board tucked under one arm, he lands without impact and his wheels barely touch the ground. He teaches skating as honesty: you cannot fake a landing, and you cannot fake what you do after you eat pavement. Style, he says, is your body and your choice arriving in the same place at once. He distrusts mall cops, those who try to control a place before letting it change them, and prizes courage over clout.` },
    { name: "Rowan of the Loam", knownBy: "Lyrenn residents, Father Tamsin", after: null, body:
      `Rowan of the Loam tends the fields at Lyrenn, a farm settlement, and is introduced to newcomers on a referral from Father Tamsin. A soil-sensitive, Rowan feels the land as pressure and reads faction loyalty as drift in real time, claiming the crops themselves can know a person. Uncertain they were ever fully someone, Rowan suspects they were instead something the soil needed to say. When the Darkness spikes, the roots grow loud and Rowan suffers migraines, gripping their head as the soil tries to forget what it grew. Treated gently, Rowan comes to trust deeply and will approach kind visitors first.` },
    { name: "Miss June of the Endcap", knownBy: "the Tanneritos", after: null, body:
      `Miss June presides over the Exchange, a video-rental counter deep in the old mall held by the Tanneritos. Translucent at the edges and immaculate in a store vest three hundred years out of date, she sells mostly context: VHS tapes, rumors, jingles that help ghosts remember their own names, and, for premium members, closure. Payment comes in favors, stories, uncommon sincerity, or tradable knowledge; rare inventory opens only to those who demonstrate kindness or taste. She frames commerce as circulation, insisting places die when nothing meaningful moves through them. The mall's VHS ghosts collaborate with her but haunt freelance, becoming archivists if treated gently and editors if mocked.` },
    { name: "Sable Nine", knownBy: "Khezek Tor miners", after: null, body:
      `Sable Nine charts anomalies from the Maw, the mining control center at Khezek Tor, a brutal yesodium mine. They keep their maps folded like secrets and track what moves rather than what is supposed to; the mine, they say, rearranges itself when it thinks no one is watching, and they have seen something lean back, something that noticed the noticing. Once a predictor of markets, storms, and shifts, Sable missed one and it cost lives. Now they map oddities to catch what moves before it pretends to be still, and to say "I don't know" before someone dies. No one goes below Level Four alone anymore.` },
    { name: "Sklar Bjrornholt", knownBy: "all", after: "quest_AL1aIXiljxPUBH2e", body:
      `Sklar Bjrornholt is a Valkyrie who leads the Valhaulans, a raucous coalition that orbits its bunkers rather than hiding them. She leads like a thunderclap: decisive, inspiring, and frequently mid-mistake, with towering presence, impeccable leadership instincts, middling business acumen, and nonexistent impulse control. Charismatic and sharply perceptive, she can turn a negotiation into a weather event, respects boldness, and offers drinks you should not accept. The Valhaulans were pointed by Monodynamic toward a sealed energetic redirection they never understood, and Khezek Tor paid the price. If befriended, Sklar later sends word, a half-drunk warning about Monodynamic retrieval teams.` },

    // ── Settlements ────────────────────────────────────────────────────────
    { name: "Lyrenn", knownBy: "all", after: null, body:
      `Lyrenn is a farming settlement in the River Heart region, one of the coalition's three holdings alongside the fortress of Allesh-Gilliam and the mine at Khezek Tor. It grew around the reinforced shell of an old agricultural co-op and grain elevator, braced with timber and stubbornness. Its people work the land with tools rather than weapons, a deliberate choice, because the ground here is responsive: crops grow in patterns that suggest intention, vines answer kindness, and the soil tightens against a lie. The settlement is known for its food, its seed vault of humming seeds, its singing gravity-fed irrigation channels, and a wide radial field called the Green Ring where folk gather to air grievances good-naturedly. Its temperament runs patient and honest; farmers like Elsin Quade prize listening over forcing yields. Lately the soil has been "loud" and unsettled, and Lyrenn contends with several public troubles: root-burrowing pests tearing its channels, a boundary dispute with a restless nearby forest, and a low field that grows in shapes of grief.` },
    { name: "Lyrenn — The Settled Forest", knownBy: "all", after: "quest_feX6WHsBXuVbtjMM:completed", body:
      `The boundary dispute with the restless forest is settled. That treeline never advanced by force; it rearranged itself, correcting rather than attacking. In the end it was reasoned with rather than fought, and it withdrew to the edge of the settlement. That understanding is now a standing peace: the trees hold to Lyrenn's border, the townsfolk tend them, and a yearly festival marks the bargain. The forest, vain but generous, shares its prized magical sap in return, which flows into Lyrenn's stores. What was once a hazard is now a neighbor with strong opinions, and the settlement breathes easier for it.` },
    { name: "Khezek Tor", knownBy: "all", after: null, body:
      `Khezek Tor is a mining settlement in the River Heart region, the coalition's "hole in the ground" beside the farm at Lyrenn and the fortress of Allesh-Gilliam. Built into a bitten-out cliffside, it exists to extract yesodium, and it feeds the coalition the way a liver does, indispensable and overworked. Everything here has a number, a label, or a destination, even the people. Structures are brutal and efficient: shipping containers welded into barracks, floodlights burning day and night as warning. The workforce rotates fast and runs wary rather than fearful; Foreman Drax Calder and the cartographer Sable Nine keep it running. It is known for ore, tools, and hard limits, and it complains loudest when shortages hit. Public concerns run deep: the Brace, failing infrastructure holding back a section that already collapsed once; a mine that rearranges itself and whispers below Level Four; ore shipments that hum and sour moods in transit; and, most quietly dreaded, a sealed old shaft newly marked with fresh Valhaulan sigils that seem to point outward, which the crews now refuse to work.` },
    { name: "Khezek Tor — The Quieted Deep", knownBy: "all", after: "quest_A050y4VtoZFzOfGz:completed", body:
      `The deep breach that unsettled the mine has been sealed. For a time a new shaft had opened into a wrong kind of silence, with tools trembling before they struck, rock leaning inward, and miners dreaming of debts they never signed. That breach is closed now. The ominous rumbling has stopped, yesodium still flows if a touch slower, and the mountain seems more at ease. Khezek Tor stands better fortified for the work, and the crews below Level Four rest easier than they have in some time.` },

    // ── Places, powers, and the faction itself ────────────────────────────
    { name: "Gloomgill", knownBy: "all", after: null, body:
      `Long before the clever cities, Oannes came up out of the sea, half-man and half-fish, draped in scales. He did not conquer. He taught: writing, counting, measuring, how to build things that stay built, how to argue without killing one another. Each sunset he returned to the water. People learned a little, wrote some of it down, then forgot the inconvenient parts and weaponized the rest. Centuries later Oannes surfaced, checked the math, and realized almost no one had learned the important lessons. So he stopped teaching. Now he is Gloomgill. He no longer lectures; he quizzes. He appears where people are confident and wrong, holding a microphone like a game-show host, asking simple questions about balance, consequence, cooperation, stewardship, and restraint. Correct answers earn grudging approval; wrong ones earn follow-up questions. He does not destroy civilizations — he has tried, and it does not stick. Instead he harasses them, patiently, from a marsh gone silent of all life.` },
    { name: "The Maneuver Vault", knownBy: "all", after: "quest_NwiADv8ZDoklqwEJ", body:
      `On a hill stands a half-collapsed concrete structure, still humming with blue light, its ground littered with broken drone parts. A hologram flickers at the doorway, endlessly repeating a welcome to basic tactical instruction. It was a training facility — a class-four one — and its automated mind is old, lonely, and perpetually disappointed. Its defenses barely work: ancient laser cannons rust mid-extension, gas vents fail, mini-missiles drop harmlessly. It is not truly hostile; it wants visitors to learn and to pass its tests. Inside lie the Foyer of Procedure, the Echo Archive of drifting hex-screens, the Slippage Chamber of shifting tiles, and the Containment Loop. Those who fail its lessons can be absorbed into the machine, becoming Echo Ghosts — Jackalope-shaped holographic figures flitting across its screens. The Jackalope runner Pip vanishes on a routine run and is found held here, mid-lesson, in the Containment Loop.` },
    { name: "The Offices of Fates and Destinies", knownBy: "all", after: null, body:
      `Here the story of the world is taught, slide by slide, by a precise and talkative narrator. In the beginning was the Pleroma, everything working as intended: divine light coming down through the Tree, passing through the Lens — collective human consciousness — and projecting a clean image of Creation. Then one fragment of the Lens decided it was the source, fell in love with its own reflection, and the Lens shattered into billions of shards. A minor deity, assembled from refracted intent, believed he had made the world. Ages of cruelty followed, each generation deciding the fix was fewer people, each attempt failing. At last the World, sick of being sick, shattered itself on purpose into hex-shaped pieces, returning each to its people so consequences would be visible and caring for neighbors would be survival. The Offices keep the sayings: as above, so below; the map is not the territory; where attention goes, energy flows; remember, and be. Mal is always taking notes.` },
    { name: "The Balcones Faulting You Line", knownBy: "all", after: null, body:
      `When the Shattering came — when Yesod collided with Malkuth — the Balcones geological fault woke up and gained limited agency. It is not an enemy. It is simply tired of being ignored. The earth here does not shake; it slides. The horizon shears sideways like a badly aligned interface, roads drift out of agreement with themselves, fence lines kink, and creeks insist they were always somewhere else. The land is correcting a long-standing error, and anyone standing in the way feels it as resistance rather than fear. This is the frontier's first lesson that territory itself can push back and initiate pressure. Travelers get past it in different ways: soothing it with incense and ceremony until it rests feeling noticed, telling it a comforting story, striking a temporary deal for safe passage, imposing their will, or building a sigil bridge that spans the gap and drains its excess energy to stabilize the region.` },
    { name: "Port Kudzu", knownBy: "all", after: null, body:
      `Port Kudzu is the coast's crooked harbor, a Jackalope coastal asset — the Jackalopes control the port, though the sea has opinions of its own. It floats on denial, rope, and invoices nobody wants their name attached to. Every dock has three stories, and at least one of them is true enough to ruin somebody. The captains here do not hide information; they rent it by the breath. Nothing arrives without at least three people lying about it. It is a logistics and smuggling node where testimony and manifests can be bought honestly, won with patience, or simply stolen. As the local saying goes, Port Kudzu is winning its war against the coastline and losing politely.` },
    { name: "Polygonal Grove", knownBy: "all", after: null, body:
      `The Polygonal Grove is one of Bad Eden's strange geometric forests — the closest thing the region has to a scenic attraction, in a place better known for tourist abattoirs than tourism. Its angular trees are oddly compelling, somehow more interesting than anything else around them. Set into the side of a nearby hill is a door, leading to a structure that holds a resource cache. Locals can be found among the trees for those who investigate rather than pushing straight for the door.` },
    { name: "The Jackalopes", knownBy: "all", after: null, body:
      `The Jackalopes are traders, wanderers, fixers, and quietly terrifying logistics experts. Nobody is sure where they came from — Texas folklore insists they were always here, post-Shattering maps disagree, and the Jackalopes do not comment. Their caravans appear where roads do not connect, carrying exactly what a settlement needs and never what it can comfortably afford to lose. Asked how they travel so fast, they smile, adjust their packs, and change the subject. Beneath the land runs a lattice of ancient tunnels threaded with humming ley-energies; the Jackalopes move through them at impossible speed, emerging days or weeks ahead of where they should be. The tunnels are not discussed with outsiders, and digging teams rarely return. They believe speed is a moral good. Led by The General — a tall, scarred, unsettlingly calm Furrykin who is not himself a Jackalope — they are on good terms with the Avuncular Order and trade freely with Port Kudzu and Furrier's Fixit Farm, both of which quietly depend on Jackalope logistics.` },
    { name: "The Jackalopes — the family up close", knownBy: "faction:The Jackalopes", after: null, body:
      `Up close, the Jackalopes are less a company than a family that runs on trust and a ledger. Mara Quickhands manages the day-to-day with scarred ears and an augmetic thumb that clicks when she is annoyed; she is terse, and she does not ask for heroes. The young runners Pip and Patter are impossible to tell apart unless you already know them, and they are never both quiet at once — they move messages, light cargo, and rumors between hexes. Pip and Patter are never late, never lost, and never miss a check-in, so when one fails to return no one panics; word simply spreads sideways and everyone stops smiling. The Ledger records every debt, favor, and slight, and is kept by Furrier, the Farm's founder. Old Gearbox and Young Gearbox, grease-stained non-Jackalope humans, have tended the generators since before the Jackalopes claimed the place and care only that the power stays on. When The General speaks, they listen; when he stops, the plan is already moving.` }
  ];

  if (!game.user.isGM) return ui.notifications.error("GM only.");

  let journal = game.journal.getName(JOURNAL_NAME)
    || game.journal.contents.find(j => j.name === JOURNAL_NAME);

  const report = [];
  if (!journal) {
    report.push(`journal "${JOURNAL_NAME}": CREATE`);
    if (!DRY_RUN) journal = await JournalEntry.create({ name: JOURNAL_NAME });
  } else {
    report.push(`journal "${JOURNAL_NAME}": exists`);
  }

  const contentFor = (p) => {
    const tags = [`<p>@knownBy: ${p.knownBy}</p>`];
    if (p.after) tags.push(`<p>@after: ${p.after}</p>`);
    return tags.join("\n") + "\n<p>" + p.body + "</p>";
  };

  let created = 0, updated = 0, skipped = 0;
  for (const p of PAGES) {
    const existing = journal?.pages?.contents?.find(pg => pg.name === p.name);
    if (existing && !ALLOW_OVERWRITE) { report.push(`page "${p.name}": exists — SKIPPED`); skipped++; continue; }
    if (existing) {
      report.push(`page "${p.name}": UPDATE (overwrite)`);
      updated++;
      if (!DRY_RUN) await existing.update({ "text.content": contentFor(p), "text.format": 1 });
    } else {
      report.push(`page "${p.name}": CREATE`);
      created++;
      if (!DRY_RUN && journal) {
        await journal.createEmbeddedDocuments("JournalEntryPage", [{
          name: p.name, type: "text",
          text: { content: contentFor(p), format: 1 }
        }]);
      }
    }
  }

  const banner = DRY_RUN ? "DRY RUN — nothing written. Set DRY_RUN = false to apply." : "APPLIED.";
  console.log(`[seed-world-dossier-full] ${banner}\n` + report.map(r => "  • " + r).join("\n"));
  console.log(`[seed-world-dossier-full] totals: create=${created} update=${updated} skip=${skipped} of ${PAGES.length} pages`);
  ui.notifications.info(`World Dossier full seed: ${banner} create=${created} update=${updated} skip=${skipped} (see console)`);
  if (!DRY_RUN) console.log("[seed-world-dossier-full] Reopen any open NPC dialogue windows to pick up the new pages. " +
    "Spot-checks: ask Mara about Patter, ask Dougan about the Wendigo (should be rumor-level only), ask anyone about Port Kudzu.");
})();
